## AWS IAM permissions in use for CI
#
#{
#    "Version": "2012-10-17",
#    "Statement": [
#        {
#            "Effect": "Allow",
#            "Action": [
#                "route53:ChangeResourceRecordSets",
#                "route53:ListResourceRecordSets"
#            ],
#            "Resource": "arn:aws:route53:::hostedzone/HOSTED-ZONE-ID-GOES-HERE"
#        },
#        {
#            "Effect": "Allow",
#            "Action": [
#                "route53:GetChange"
#            ],
#            "Resource": "arn:aws:route53:::change/*"
#        },
#        {
#            "Effect": "Allow",
#            "Action": "route53:ListHostedZonesByName",
#            "Resource": "*"
#        }
#    ]
#}

language: minimal
before_install:
  - sudo apt-get update
before_script:
  # we need cli53 to import hosted zone files because it's easier that writing a whole bunch of code to do it
  - curl -L https://github.com/barnybug/cli53/releases/latest/download/cli53-linux-amd64 --output cli53-linux-amd64
  - sudo mv cli53-linux-amd64 /usr/local/bin/cli53
  - sudo chmod +x /usr/local/bin/cli53
script:
  # Note: HOSTED_ZONE_ID needs to be set as an environment variable
  - |
    cli53 import --file adventure.craig.mayhew.io.txt --replace --wait --dry-run adventure.craig.mayhew.io
    cli53 import --file adventure.craig.mayhew.io.txt --replace --wait adventure.craig.mayhew.io


notifications:
  email:
    on_failure: always
    on_success: never
